"""College football conference metadata and AP poll rankings.

The scoreboard mode needs to turn ~99 live FBS games into "just my top 25" or
"just the SEC" and needs a favourites picker where 134+ teams aren't a flat
unusable list. That requires two things ESPN's scoreboard endpoint doesn't
carry on its own: a conference id -> name/short mapping, and a team id ->
conference id lookup so `competitor.team.conferenceId` (or `curatedRank`)
means something to a human.

Both tables below were derived by probing ESPN's group tree once (FBS is
group 80, its children are the 11 FBS conferences, each conference group has
a `teams` link) and pasting the result here as a literal. No network call is
made at import time or ever, for these two tables -- conference membership
changes maybe once a year via realignment, not worth a live fetch (and
definitely not worth a failure mode that can take the scoreboard down).

Rankings are different: the AP poll changes weekly during the season, so
`Rankings` does fetch live, but through a small TTL cache that always has a
last-good fallback -- any network or parse failure degrades to "no rankings"
rather than raising.

Conference ids match `team.conferenceId` as returned by ESPN's site API
(verified against a live groups=80 scoreboard pull), so callers can use
`conference_of(team_id)` to interpret it or just trust the field they already
have and use `conference_name()` to display it.
"""

import time
import urllib.request
import json

# Sorted power conferences first (SEC, Big Ten, ACC, Big 12 -- the four that
# actually decide the CFP), then the rest alphabetical by name. Matches how
# a viewer picking "which conferences do I care about" would scan the list.
CONFERENCES = [
    {"id": "8", "name": "SEC", "short": "SEC"},
    {"id": "5", "name": "Big Ten", "short": "B1G"},
    {"id": "1", "name": "ACC", "short": "ACC"},
    {"id": "4", "name": "Big 12", "short": "B12"},
    {"id": "151", "name": "American", "short": "AAC"},
    {"id": "12", "name": "Conference USA", "short": "CUSA"},
    {"id": "18", "name": "FBS Independents", "short": "IND"},
    {"id": "15", "name": "Mid-American", "short": "MAC"},
    {"id": "17", "name": "Mountain West", "short": "MWC"},
    {"id": "9", "name": "Pac-12", "short": "PAC"},
    {"id": "37", "name": "Sun Belt", "short": "SBC"},
]

_CONF_NAME_BY_ID = {c["id"]: c["name"] for c in CONFERENCES}

# team id -> conference id, one block per conference, comment gives the
# count found when this was last derived (138 FBS teams, Aug 2026).
# Generated by tools/gen_cfb_conferences.py -- 138 FBS teams, 2026 season.
# conference id -> [(team id, abbreviation, name)]
CONFERENCE_TEAMS = {
    # SEC (16)
    "8": [
        ("333", "ALA", 'Alabama'),
        ("8", "ARK", 'Arkansas'),
        ("2", "AUB", 'Auburn'),
        ("57", "FLA", 'Florida'),
        ("61", "UGA", 'Georgia'),
        ("96", "UK", 'Kentucky'),
        ("99", "LSU", 'LSU'),
        ("344", "MSST", 'Mississippi State'),
        ("142", "MIZ", 'Missouri'),
        ("201", "OU", 'Oklahoma'),
        ("145", "MISS", 'Ole Miss'),
        ("2579", "SC", 'South Carolina'),
        ("2633", "TENN", 'Tennessee'),
        ("251", "TEX", 'Texas'),
        ("245", "TA&M", 'Texas A&M'),
        ("238", "VAN", 'Vanderbilt'),
    ],
    # Big Ten (18)
    "5": [
        ("356", "ILL", 'Illinois'),
        ("84", "IU", 'Indiana'),
        ("2294", "IOWA", 'Iowa'),
        ("120", "MD", 'Maryland'),
        ("130", "MICH", 'Michigan'),
        ("127", "MSU", 'Michigan State'),
        ("135", "MINN", 'Minnesota'),
        ("158", "NEB", 'Nebraska'),
        ("77", "NU", 'Northwestern'),
        ("194", "OSU", 'Ohio State'),
        ("2483", "ORE", 'Oregon'),
        ("213", "PSU", 'Penn State'),
        ("2509", "PUR", 'Purdue'),
        ("164", "RUTG", 'Rutgers'),
        ("26", "UCLA", 'UCLA'),
        ("30", "USC", 'USC'),
        ("264", "WASH", 'Washington'),
        ("275", "WIS", 'Wisconsin'),
    ],
    # ACC (17)
    "1": [
        ("103", "BC", 'Boston College'),
        ("25", "CAL", 'California'),
        ("228", "CLEM", 'Clemson'),
        ("150", "DUKE", 'Duke'),
        ("52", "FSU", 'Florida State'),
        ("59", "GT", 'Georgia Tech'),
        ("97", "LOU", 'Louisville'),
        ("2390", "MIA", 'Miami'),
        ("152", "NCSU", 'NC State'),
        ("153", "UNC", 'North Carolina'),
        ("221", "PITT", 'Pittsburgh'),
        ("2567", "SMU", 'SMU'),
        ("24", "STAN", 'Stanford'),
        ("183", "SYR", 'Syracuse'),
        ("258", "UVA", 'Virginia'),
        ("259", "VT", 'Virginia Tech'),
        ("154", "WAKE", 'Wake Forest'),
    ],
    # Big 12 (16)
    "4": [
        ("12", "ARIZ", 'Arizona'),
        ("9", "ASU", 'Arizona State'),
        ("252", "BYU", 'BYU'),
        ("239", "BAY", 'Baylor'),
        ("2132", "CIN", 'Cincinnati'),
        ("38", "COLO", 'Colorado'),
        ("248", "HOU", 'Houston'),
        ("66", "ISU", 'Iowa State'),
        ("2305", "KU", 'Kansas'),
        ("2306", "KSU", 'Kansas State'),
        ("197", "OKST", 'Oklahoma State'),
        ("2628", "TCU", 'TCU'),
        ("2641", "TTU", 'Texas Tech'),
        ("2116", "UCF", 'UCF'),
        ("254", "UTAH", 'Utah'),
        ("277", "WVU", 'West Virginia'),
    ],
    # American (14)
    "151": [
        ("349", "ARMY", 'Army'),
        ("2429", "CLT", 'Charlotte'),
        ("151", "ECU", 'East Carolina'),
        ("2226", "FAU", 'Florida Atlantic'),
        ("235", "MEM", 'Memphis'),
        ("2426", "NAVY", 'Navy'),
        ("249", "UNT", 'North Texas'),
        ("242", "RICE", 'Rice'),
        ("58", "USF", 'South Florida'),
        ("218", "TEM", 'Temple'),
        ("2655", "TULN", 'Tulane'),
        ("202", "TLSA", 'Tulsa'),
        ("5", "UAB", 'UAB'),
        ("2636", "UTSA", 'UTSA'),
    ],
    # Conference USA (10)
    "12": [
        ("48", "DEL", 'Delaware'),
        ("2229", "FIU", 'Florida International'),
        ("55", "JVST", 'Jacksonville State'),
        ("338", "KENN", 'Kennesaw State'),
        ("2335", "LIB", 'Liberty'),
        ("2393", "MTSU", 'Middle Tennessee'),
        ("2623", "MOST", 'Missouri State'),
        ("166", "NMSU", 'New Mexico State'),
        ("2534", "SHSU", 'Sam Houston'),
        ("98", "WKU", 'Western Kentucky'),
    ],
    # FBS Independents (2)
    "18": [
        ("87", "ND", 'Notre Dame'),
        ("41", "CONN", 'UConn'),
    ],
    # Mid-American (13)
    "15": [
        ("2006", "AKR", 'Akron'),
        ("2050", "BALL", 'Ball State'),
        ("189", "BGSU", 'Bowling Green'),
        ("2084", "BUFF", 'Buffalo'),
        ("2117", "CMU", 'Central Michigan'),
        ("2199", "EMU", 'Eastern Michigan'),
        ("2309", "KENT", 'Kent State'),
        ("113", "MASS", 'Massachusetts'),
        ("193", "M-OH", 'Miami (OH)'),
        ("195", "OHIO", 'Ohio'),
        ("16", "SAC", 'Sacramento State'),
        ("2649", "TOL", 'Toledo'),
        ("2711", "WMU", 'Western Michigan'),
    ],
    # Mountain West (10)
    "17": [
        ("2005", "AFA", 'Air Force'),
        ("62", "HAW", "Hawai'i"),
        ("2440", "NEV", 'Nevada'),
        ("167", "UNM", 'New Mexico'),
        ("2449", "NDSU", 'North Dakota State'),
        ("2459", "NIU", 'Northern Illinois'),
        ("23", "SJSU", 'San José State'),
        ("2439", "UNLV", 'UNLV'),
        ("2638", "UTEP", 'UTEP'),
        ("2751", "WYO", 'Wyoming'),
    ],
    # Pac-12 (8)
    "9": [
        ("68", "BOIS", 'Boise State'),
        ("36", "CSU", 'Colorado State'),
        ("278", "FRES", 'Fresno State'),
        ("204", "ORST", 'Oregon State'),
        ("21", "SDSU", 'San Diego State'),
        ("326", "TXST", 'Texas State'),
        ("328", "USU", 'Utah State'),
        ("265", "WSU", 'Washington State'),
    ],
    # Sun Belt (14)
    "37": [
        ("2026", "APP", 'App State'),
        ("2032", "ARST", 'Arkansas State'),
        ("324", "CCU", 'Coastal Carolina'),
        ("290", "GASO", 'Georgia Southern'),
        ("2247", "GAST", 'Georgia State'),
        ("256", "JMU", 'James Madison'),
        ("309", "UL", 'Louisiana'),
        ("2348", "LT", 'Louisiana Tech'),
        ("276", "MRSH", 'Marshall'),
        ("295", "ODU", 'Old Dominion'),
        ("6", "USA", 'South Alabama'),
        ("2572", "USM", 'Southern Miss'),
        ("2653", "TROY", 'Troy'),
        ("2433", "ULM", 'UL Monroe'),
    ],
}

# team id -> conference id, inverted from the generated table so there is one
# source of truth for membership.
TEAM_CONFERENCE = {
    tid: cid for cid, teams in CONFERENCE_TEAMS.items() for tid, _, _ in teams
}

_RANKINGS_URL = (
    "https://site.api.espn.com/apis/site/v2/sports/football/college-football/rankings"
)
_RANKINGS_TTL = 600  # seconds; AP poll updates weekly, 10 min is plenty fresh


def conference_of(team_id) -> str:
    return TEAM_CONFERENCE.get(str(team_id), "")


def conference_name(conf_id) -> str:
    return _CONF_NAME_BY_ID.get(str(conf_id), "")


class Rankings:
    """TTL-cached AP Top 25 / receiving-votes fetcher.

    Never raises. On any network or parse problem it keeps serving whatever
    it last fetched successfully (or an empty result if it's never
    succeeded) -- a bad poll fetch should never be able to blank the
    scoreboard mode.
    """

    def __init__(self, ttl: float = _RANKINGS_TTL):
        self._ttl = ttl
        self._fetched_at = 0.0
        self._ranks: list[dict] = []   # top 25, in order
        self._others: list[dict] = []  # next 25 "receiving votes", in order

    def _refresh(self) -> None:
        if time.time() - self._fetched_at < self._ttl:
            return
        try:
            # No custom headers -- ESPN's edge 403s a couple of User-Agent
            # strings that urllib.request.Request would otherwise send by
            # default; plain urlopen() matches what a browser/default client
            # gets and has been reliable.
            with urllib.request.urlopen(_RANKINGS_URL, timeout=5) as resp:
                data = json.load(resp)
            ap = next(
                r for r in data.get("rankings", []) if r.get("shortName") == "AP Poll"
            )
            ranks = [self._entry(e) for e in ap.get("ranks", [])]
            others = [self._entry(e) for e in ap.get("others", [])]
            ranks = [e for e in ranks if e is not None]
            others = [e for e in others if e is not None]
            if ranks:
                self._ranks = ranks
                self._others = others
                self._fetched_at = time.time()
        except Exception:
            # Keep serving the last good data (or empty, if we never had any).
            pass

    @staticmethod
    def _entry(e):
        try:
            team_id = str(e["team"]["id"])
            current = int(e["current"])
            return {"team_id": team_id, "current": current}
        except (KeyError, TypeError, ValueError):
            return None

    def top(self, n: int) -> set:
        self._refresh()
        try:
            n = int(n)
        except (TypeError, ValueError):
            return set()
        if n <= 0:
            return set()
        if n <= 25:
            pool = self._ranks[:n]
        else:
            pool = (self._ranks + self._others)[:n]
        return {e["team_id"] for e in pool}

    def rank_of(self, team_id):
        self._refresh()
        team_id = str(team_id)
        for e in self._ranks:
            if e["team_id"] == team_id:
                return e["current"]
        return None


# -- teams grouped by conference, for the favourites picker ------------------
#
# 138 FBS teams as one flat list is unusable to pick from, so the control
# center gets them pre-grouped the way people actually think about college
# football.
#
# Names are baked into CONFERENCE_TEAMS rather than looked up at runtime. The
# earlier version fetched them from the site API's /teams?limit=900 and dropped
# any team the response didn't contain -- and that endpoint caps well below 900,
# so Air Force, Buffalo and Jacksonville State silently fell off the end of the
# list and could not be favourited. A picker that quietly omits teams is worse
# than one that needs regenerating once a year.


def cfb_teams_by_conference() -> list:
    """[{"id","name","short","teams":[{"abbrev","name","id"}]}], conference order."""
    out = []
    for conf in CONFERENCES:
        teams = [
            {"id": tid, "abbrev": abbrev, "name": name}
            for tid, abbrev, name in CONFERENCE_TEAMS.get(conf["id"], [])
        ]
        teams.sort(key=lambda t: t["name"])
        if teams:
            out.append({**conf, "teams": teams})
    return out
