"""Regenerate FBS conference membership in app/sources/cfb_meta.py from ESPN.

Run once a year, after realignment:

    .venv/bin/python tools/gen_cfb_conferences.py 2027

Membership is generated rather than hand-maintained, because hand-maintaining
it is how Air Force, Buffalo, UMass, UConn and Jacksonville State went missing
from the favourites picker -- a team absent from the table is simply
unfavouritable, and nothing surfaces the omission.

Two ESPN traps this works around, both of which fail by returning plausible
wrong data rather than erroring:

  * The site API's /teams?groups=<id> IGNORES `groups` and returns every team
    in every division for any id you pass, so all eleven conferences come back
    identical. The core API's per-group teams resource actually filters.
  * The site API's /teams?limit=900 is capped server-side well below 900, so
    FBS teams past the cut vanish. That's why names are baked in here instead
    of being looked up at runtime.
"""

import concurrent.futures as cf
import io
import re
import sys

import requests

GROUP_TEAMS = (
    "https://sports.core.api.espn.com/v2/sports/football/leagues/college-football"
    "/seasons/{year}/types/2/groups/{gid}/teams?limit=100"
)


def members(gid, year):
    refs = requests.get(GROUP_TEAMS.format(gid=gid, year=year), timeout=20).json()["items"]
    with cf.ThreadPoolExecutor(8) as pool:
        teams = list(pool.map(lambda r: requests.get(r["$ref"], timeout=20).json(), refs))
    out = [
        (t["id"], (t.get("abbreviation") or "").upper(), t.get("location", ""))
        for t in teams
        if t.get("abbreviation")
    ]
    return sorted(out, key=lambda x: x[2])


def main(year=2026):
    sys.path.insert(0, ".")
    from app.sources.cfb_meta import CONFERENCES

    lines, total = [], 0
    for c in CONFERENCES:
        ts = members(c["id"], year)
        total += len(ts)
        lines.append(f'    # {c["name"]} ({len(ts)})')
        lines.append(f'    "{c["id"]}": [')
        for tid, abbrev, loc in ts:
            lines.append(f'        ("{tid}", "{abbrev}", {loc!r}),')
        lines.append("    ],")

    block = (
        f"# Generated by tools/gen_cfb_conferences.py -- {total} FBS teams, "
        f"{year} season.\n"
        "# conference id -> [(team id, abbreviation, name)]\n"
        "CONFERENCE_TEAMS = {\n" + "\n".join(lines) + "\n}"
    )
    p = "app/sources/cfb_meta.py"
    src = io.open(p, encoding="utf-8").read()
    pat = r"# Generated by tools/gen_cfb_conferences\.py.*?\nCONFERENCE_TEAMS = \{.*?\n\}"
    if re.search(pat, src, flags=re.S):
        new = re.sub(pat, block, src, count=1, flags=re.S)
    else:  # first run: replace the old hand-written table
        new = re.sub(r"TEAM_CONFERENCE = \{.*?\n\}", block, src, count=1, flags=re.S)
    if new == src:
        raise SystemExit("could not locate the table to replace")
    io.open(p, "w", encoding="utf-8").write(new)
    print(f"wrote {total} teams across {len(CONFERENCES)} conferences to {p}")


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 2026)
